### ISSUE TITLE
xm2 deletes monopropellant

### ISSUE THREAD

**Issue by Cactronaut** [quetschke/kOSutil#1]
XM2.ks uses all monopropellant on board to maintain target when reaction wheels more than good enough

**Comment by quetschke** [comment]
Sorry, somehow I didn't get the notification from GitHub. I ran into the same issue and it is fixed in the version I just pushed. Now xm2 will only use RCS if it is enabled before running the script. Please try it out.

**Comment by quetschke** [comment]
Fixed in c37525d .
